### ISSUE TITLE
'Newtonsoft.Json.JsonSerializationException: Self referencing loop detected' when using some classes as properties in examples

### ISSUE THREAD

**Issue by leonardo-gooten** [vaclavnovotny/NSwag.Examples#11]
I'm getting following error when I define one Swagger example whose class has a property that has self referencing loop, like the class JsonSchema from https://www.nuget.org/packages/JsonSchema.Net/3.3.2 or JsonObject from https://docs.microsoft.com/en-us/dotnet/api/system.json.jsonobject?view=dotnet-plat-ext-7.0 .

> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'root' with type 'System.Text.Json.Nodes.JsonValueTrimmable`1[System.Text.Json.JsonElement]'. Path 'schema.keywords[2].properties.hasCobrandedHub.keywords[0].value'.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
>    at NSwag.Examples.RequestBodyExampleProcessor.Process(OperationProcessorContext context)
>    at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
>    at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
>    at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
>    at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
>    at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
>    at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
>    at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

![image](https://user-images.githubusercontent.com/113933580/224571523-66a66ad4-e23a-4a77-ae73-fb453f3795c1.png)

![image](https://user-images.githubusercontent.com/113933580/224572021-cc1823d4-cd8b-4dba-89b0-f08e3610bf78.png)

Normally this kind of error can be solved by adding a code like this to your project, if it's MVC
```
    builder.Services.AddControllers().AddJsonOptions(x =>
    {
        x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
        x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    });
```
or something like this 
```
    JsonConvert.DefaultSettings = () => new JsonSerializerSettings
    {
        Formatting = Newtonsoft.Json.Formatting.Indented,
        ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
    };
```
I also tried adding annotation to the property or the class
```
public class ConfigSchemaDto
{
    public string Id { get; set; }
    [JsonProperty(IsReference = true)]
    public JsonSchema Schema { get; set; }
}
```
```
[JsonObject(IsReference = true)]
public class ConfigSchemaDto
{
    public string Id { get; set; }
    public JsonSchema Schema { get; set; }
}
```
but nothing worked.

The JsonSchema in question was generated from 
```
JsonSchema.FromText(@"{
            ""notificationType"": ""Sms"",
            ""hasCobrandedHub"": false,
            ""isSKUSubstitutionEnabled"": false,
            ""generalDiscountPercentage"": 0
        }"), 
```
Not that this matters, just putting here for completion, so that the error message makes more sense, because it talks about some of the properties in here.

My guess is that I would need to change the whey NSwag.Examples serializes, to disable the loop directly, because the serializairon options that I provided, only affect the .Net MVC API, not the one used by NSwag.Examples.
Can you help?

**Comment by leonardo-gooten** [comment]
Ok.. I got it working... by adding serialization options to the code needed to use this library :-) 
```
services.AddOpenApiDocument((documentSettings, serviceProvider) =>
{
          documentSettings.AddExamples(serviceProvider);
          documentSettings.SerializerSettings = new Newtonsoft.Json.JsonSerializerSettings
          {
              ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
          };
}
```
