### ISSUE TITLE
Request Body automatic addition of examples defined for properties

### ISSUE THREAD

**Issue by toutas** [vaclavnovotny/NSwag.Examples#26]
I have the following request body class:

```csharp
public class PostTaskOrderEstimateCommand : IRequestWrapper<TaskOrderDto>
{
    public string? Wkt { get; set; }
    public GeoJsonGeometryDto? GeoJson { get; set; }
}
```

I have defined an example for `PostTaskOrderCommand `:

```csharp
public class PostTaskOrderEstimateCommandExample : IExampleProvider<PostTaskOrderEstimateCommand>
{
    public PostTaskOrderEstimateCommand GetExample()
    {
        PostTaskOrderEstimateCommand result = new PostTaskOrderEstimateCommand
        {
            Wkt = "GEOMETRYCOLLECTION (MULTIPOLYGON (((9.157104 55.976872, 9.157104 56.12106, 9.371338 56.12106, 9.371338 55.976872, 9.157104 55.976872)), ((9.030762 56.362207, 8.948364 56.295205, 9.041748 56.26166, 9.140625 56.286059, 9.030762 56.362207))), POLYGON ((10.288696 56.114936, 10.05249 56.133307, 9.986572 56.0475, 10.101929 56.004524, 10.288696 56.114936)), POLYGON ((11.640015 55.615589, 11.876221 55.590763, 11.694946 55.491304, 11.640015 55.615589)), POLYGON ((11.65 55.62, 11.651 55.62, 11.65 55.621, 11.65 55.62)), MULTIPOLYGON (((11.652 55.622, 11.653 55.622, 11.652 55.623, 11.652 55.622)), ((11.654 55.624, 11.655 55.624, 11.654 55.625, 11.654 55.624))))",
        };

        return result;
    }
}
```

The documentation that is generated shows the `PostTaskOrderEstimateCommandExample `as expected, but I have another example defined for `GeoJsonGeometryDto`:

```csharp
public class GeoJsonGeometryDtoExample : IExampleProvider<GeoJsonGeometryDto>
{
    public GeoJsonGeometryDto GetExample()
    {
        var result = new GeoJsonGeometryDto()
        {
            Type = "GeometryCollection",
            Geometries =
            [
                new GeoJsonGeometryDto()
                {
                    Type = "MultiPolygon",
                    Coordinates = new double[][][][]
                    {
                        [
                            [
                                [9.157104, 55.976872],
                                [9.157104, 56.12106],
                                [9.371338, 56.12106],
                                [9.371338, 55.976872],
                                [9.157104, 55.976872]
                            ],
                            [
                                [9.030762, 56.362207],
                                [8.948364, 56.295205],
                                [9.041748, 56.26166],
                                [9.140625, 56.286059],
                                [9.030762, 56.362207]
                            ]
                        ]
                    },
                },
                new GeoJsonGeometryDto()
                {
                    Type = "MultiPolygon",
                    Coordinates = new double[][][][]
                    {
                        [
                            [
                                [11.652, 55.622],
                                [11.653, 55.622],
                                [11.652, 55.623],
                                [11.652, 55.622]
                            ],
                            [
                                [11.654, 55.624],
                                [11.655, 55.624],
                                [11.654, 55.625],
                                [11.654, 55.624]
                            ]
                        ]
                    },
                },
                new GeoJsonGeometryDto()
                {
                    Type = "Polygon",
                    Coordinates = new double[][][]
                    {
                        [
                            [10.288696, 56.114936],
                            [10.05249, 56.133307],
                            [9.986572, 56.0475],
                            [10.101929, 56.004524],
                            [10.288696, 56.114936]
                        ]
                    },
                },
                new GeoJsonGeometryDto()
                {
                    Type = "Polygon",
                    Coordinates = new double[][][]
                    {
                        [
                            [11.640015, 55.615589],
                            [11.876221, 55.590763],
                            [11.694946, 55.491304],
                            [11.640015, 55.615589]
                        ]
                    },
                },
                new GeoJsonGeometryDto()
                {
                    Type = "Polygon",
                    Coordinates = new double[][][]
                    {
                        [
                            [11.650, 55.620],
                            [11.651, 55.620],
                            [11.650, 55.621],
                            [11.650, 55.620]
                        ]
                    },
                },
            ]
        };

        return result;
    }
}
```

Is there any way to force/nudge this example to be used when the GeoJsonGeometryDto is a property on a body?

Currently the documentation just shows:

```json
{
"Wkt": "GEOMETRYCOLLECTION (MULTIPOLYGON (((9.157104 55.976872, 9.157104 56.12106, 9.371338 56.12106, 9.371338 55.976872, 9.157104 55.976872)), ((9.030762 56.362207, 8.948364 56.295205, 9.041748 56.26166, 9.140625 56.286059, 9.030762 56.362207))), POLYGON ((10.288696 56.114936, 10.05249 56.133307, 9.986572 56.0475, 10.101929 56.004524, 10.288696 56.114936)), POLYGON ((11.640015 55.615589, 11.876221 55.590763, 11.694946 55.491304, 11.640015 55.615589)), POLYGON ((11.65 55.62, 11.651 55.62, 11.65 55.621, 11.65 55.62)), MULTIPOLYGON (((11.652 55.622, 11.653 55.622, 11.652 55.623, 11.652 55.622)), ((11.654 55.624, 11.655 55.624, 11.654 55.625, 11.654 55.624))))",
"GeoJson": null
}
```

but I would like the GeoJson example to fill out the GeoJson property for the example.

**Comment by vaclavnovotny** [comment]
Hello @toutas!
It is possible to "nudge" GeoJsonGeometryDtoExample into the PostTaskOrderEstimateCommandExample by using dependency injection supported by NSwag.Examples.
Consider following approach:

```csharp
public class PostTaskOrderEstimateCommandExample : IExampleProvider<PostTaskOrderEstimateCommand>
{
    private readonly IExampleProvider<GeoJsonGeometryDtoExample> _geoJsonExample;

    public PostTaskOrderEstimateCommandExample(IExampleProvider<GeoJsonGeometryDtoExample> geoJsonExample) {
        _geoJsonExample = geoJsonExample;
    }

    public PostTaskOrderEstimateCommand GetExample()
    {
        PostTaskOrderEstimateCommand result = new PostTaskOrderEstimateCommand
        {
            Wkt = "GEOMETRYCOLLECTION (MULTIPOLYGON (((9.157104 55.976872, 9.157104 56.12106, 9.371338 56.12106, 9.371338 55.976872, 9.157104 55.976872)), ((9.030762 56.362207, 8.948364 56.295205, 9.041748 56.26166, 9.140625 56.286059, 9.030762 56.362207))), POLYGON ((10.288696 56.114936, 10.05249 56.133307, 9.986572 56.0475, 10.101929 56.004524, 10.288696 56.114936)), POLYGON ((11.640015 55.615589, 11.876221 55.590763, 11.694946 55.491304, 11.640015 55.615589)), POLYGON ((11.65 55.62, 11.651 55.62, 11.65 55.621, 11.65 55.62)), MULTIPOLYGON (((11.652 55.622, 11.653 55.622, 11.652 55.623, 11.652 55.622)), ((11.654 55.624, 11.655 55.624, 11.654 55.625, 11.654 55.624))))",
        };
        GeoJson = _geoJsonExample.GetExample();

        return result;
    }
}

```

You can resolve your already defined example of `GeoJsonGeometry` from the constructor and use the available method `GetExample`.
Does this work for you?

**Comment by toutas** [comment]
thanks for your response @vaclavnovotny,

I attempted the approach you described, but ended up getting the following build error. it seems like the DI is not able to supply the IExampleProvider<GeoJsonGeometryDtoExample>. Do I need to setup something separate to allow nswag to retrieve the iexampleprovider using DI?

```csharp
public class PostTaskOrderCommandExample : IExampleProvider<PostTaskOrderCommand>
{
    private readonly IExampleProvider<GeoJsonGeometryDtoExample> _geoJsonGeometryDtoExampleProvider;

    public PostTaskOrderCommandExample(IExampleProvider<GeoJsonGeometryDtoExample> geoJsonGeometryDtoExampleProvider)
    {
        _geoJsonGeometryDtoExampleProvider = geoJsonGeometryDtoExampleProvider;
    }

    public PostTaskOrderCommand GetExample()
    {

        GeoJsonGeometryDtoExample geoJsonExample = _geoJsonGeometryDtoExampleProvider.GetExample();

        PostTaskOrderCommand result = new PostTaskOrderCommand
        {
            StorageMonths = 3,
            ApiRequests = 5,
            SatelliteConstellations = new List<SatelliteConstellation> { SatelliteConstellation.Sentinel1, SatelliteConstellation.Sentinel2, SatelliteConstellation.Landsat89 },
            Model = PredictionModel.Zephyr,
            Wkt = "GEOMETRYCOLLECTION (MULTIPOLYGON (((9.157104 55.976872, 9.157104 56.12106, 9.371338 56.12106, 9.371338 55.976872, 9.157104 55.976872)), ((9.030762 56.362207, 8.948364 56.295205, 9.041748 56.26166, 9.140625 56.286059, 9.030762 56.362207))), POLYGON ((10.288696 56.114936, 10.05249 56.133307, 9.986572 56.0475, 10.101929 56.004524, 10.288696 56.114936)), POLYGON ((11.640015 55.615589, 11.876221 55.590763, 11.694946 55.491304, 11.640015 55.615589)), POLYGON ((11.65 55.62, 11.651 55.62, 11.65 55.621, 11.65 55.62)), MULTIPOLYGON (((11.652 55.622, 11.653 55.622, 11.652 55.623, 11.652 55.622)), ((11.654 55.624, 11.655 55.624, 11.654 55.625, 11.654 55.624))))",
            ReferenceDate = new DateOnly(2023, 6, 1),
            From = new DateOnly(2023, 6, 1),
            ImageFrequency = 2,
            GeoJson = geoJsonExample.GetExample()
        };

        return result;
    }
}
```

```yaml
1>Hub.Api -> F:\Projects\CSV\hub\src\Apps\Hub.Api\bin\Debug\net8.0\Hub.Api.dll
1>NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
1>Visit http://NSwag.org for more information.
1>NSwag bin directory: C:\Users\mypc\.nuget\packages\nswag.msbuild\14.1.0\tools\Net80
1>
1>Executing file 'nswag.json' with variables 'Configuration=Debug'...
1>Launcher directory: C:\Users\mypc\.nuget\packages\nswag.msbuild\14.1.0\tools\Net80
1>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.InvalidOperationException: Unable to resolve service for type 'NSwag.Examples.IExampleProvider`1[Hub.Api.Documentation.Examples.GeoJsonGeometryDtoExample]' while attempting to activate 'Hub.Api.Documentation.Examples.PostTaskOrderCommandExample'.
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
1>   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
1>   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
1>   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
1>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
1>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
1>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
1>   at NSwag.Examples.SwaggerExampleProvider.GetProviderValues(Type valueType, IEnumerable`1 exampleTypes, ExampleType exampleType)+MoveNext()
1>   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
1>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
1>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
1>   at NSwag.Examples.ExamplesConverter.ToOpenApiExamplesDictionary(IEnumerable`1 examples)
1>   at NSwag.Examples.RequestBodyExampleProcessor.GetExamples(SwaggerExampleProvider exampleProvider, Type valueType, IEnumerable`1 exampleTypes, ExampleType exampleType)
1>   at NSwag.Examples.RequestBodyExampleProcessor.SetRequestExamples(OperationProcessorContext context, SwaggerExampleProvider exampleProvider)
1>   at NSwag.Examples.RequestBodyExampleProcessor.Process(OperationProcessorContext context)
1>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator generator, OpenApiSchemaResolver schemaResolver)
1>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
1>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocumentGenerator generator, OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
1>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 245
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.GenerateDocumentAsync(IServiceProvider serviceProvider, String currentWorkingDirectory) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 239
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
1>   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
1>   --- End of inner exception stack trace ---
1>   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
1>   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
1>   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132
1>System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 195
1>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 270
1>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 67
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 76
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 33
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 65
1>F:\Projects\CSV\hub\src\Apps\Hub.Api\Hub.Api.csproj(75,3): error MSB3073: The command "dotnet "C:\Users\mypc\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code -1.
1>Done building project "Hub.Api.csproj" -- FAILED.
```

**Comment by toutas** [comment]
@vaclavnovotny thank you for your suggestion, it worked out perfectly!

I made a mistake in defining the IExampleProvider to retrieve using DI, but it works exactly as I was hoping. 

Thank you for helping out, just started checking out your solution for setting up examples and I'm loving it so far.
