### ISSUE TITLE
Swagger/openapi specification generation fails, if controller method contains a [FromForm] attribute

### ISSUE THREAD

**Issue by BartBr** [vaclavnovotny/NSwag.Examples#6]
the following method in a controller results in a NullReferenceException.
`public async Task<IActionResult> Upload([FromForm] file) { .. }`

Line 32 in the RequestBodyExampleProcessor results in an empty(default) KeyValuePair
`var parameter = context.Parameters.SingleOrDefault(x => x.Value.Name == apiParameter.Name);`

ExceptionMessage:
System.NullReferenceException: Object reference not set to an instance of an object.
StackTrace:
```
   at NSwag.Examples.RequestBodyExampleProcessor.Process(OperationProcessorContext context)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.<GenerateAsync>d__6.MoveNext()
```

**Comment by vaclavnovotny** [comment]
Hey @BartBr, sorry for the long delay. I have merged this [PR](https://github.com/vaclavnovotny/NSwag.Examples/pull/7) which fixes your issue and package 1.0.7 has been released.
